name: CI A

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Artificial 5 seconds delay
        run: sleep 5

      - name: Hello world
        run: echo "Hello, world!"
