name: Run after CI A and CI B

on:
  workflow_run:
    #https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#workflow_run
    # This fires after either workflow from the list fires its workflow event
    # (in that case, "complete"). Meaning: this is an OR rule. To make an AND
    # rule, we need to check the status of all the dependencies from the list.
    workflows: ["CI A", "CI B"]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_sha }}
  cancel-in-progress: true

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Hello world
        run: echo "Hello, world!"

      - name: Dump event data
        run: |
          echo "calling commit: ${{ toJson(github.event.workflow_run.head_sha) }}"
          echo "calling workflow: ${{ toJson(github.event.workflow_run.workflow) }}"
          echo "calling run_id: ${{ toJson(github.event.workflow_run.run_id) }}"

      - name: Get workflow dependencies
        id: workflow_dependencies
        run: |
          # Extract path from "owner/repo/.github/workflows/file.yml@refs/heads/main"
          WORKFLOW_PATH="${GITHUB_WORKFLOW_REF#*/}"   # strip "owner/"
          WORKFLOW_PATH="${WORKFLOW_PATH#*/}"         # strip "repo/"
          WORKFLOW_PATH="${WORKFLOW_PATH%@*}"         # strip "@ref"

          WORKFLOWS=$(yq -o=json -I=0 '.on.workflow_run.workflows' "$WORKFLOW_PATH")
          echo "list=$WORKFLOWS" >> $GITHUB_OUTPUT

      - name: Dump workflow dependencies
        run: |
          echo "workflow dependencies: ${{ toJson(steps.workflow_dependencies.outputs.list) }}"

      - name: Check all workflow dependencies status
        env:
          GH_TOKEN: ${{ github.token }}
          HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
          DEPENDENCIES: ${{ steps.workflow_dependencies.outputs.list }}
          # Whether it is enough to wait for workflows to complete (regardless
          # of their conclusion), or whether we need them all to succeed
          DEPENDENCIES_MUST_PASS: false
        run: bun .github/scripts/check-workflow-dependencies.ts
