name: Run after CI A and CI B

on:
  workflow_run:
    #https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#workflow_run
    # This fires after either workflow from the list fires its workflow event
    # (in that case, "complete"). Meaning: this is an OR rule. To make an AND
    # rule, we need to check the status of all the dependencies from the list.
    workflows: ["CI A", "CI B"]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_sha }}
  cancel-in-progress: true

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Hello world
        run: echo "Hello, world!"

      - name: Dump event data
        run: |
            echo "calling commit: ${{ toJson(github.event.workflow_run.head_sha) }}"
